#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun May 08 18:05:02 CEST 2022
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_1_behav -key {Behavioral:sim_1:Functional:tb_1} -tclbatch tb_1.tcl -view /home/aelysium/OneDrive/Polimi/3o_anno/reti_logiche/progetto/progetto_rl/tb_1_behav.wcfg -view /home/aelysium/OneDrive/Polimi/3o_anno/reti_logiche/progetto/progetto_rl/tb_1_func_synth.wcfg -log simulate.log"
xsim tb_1_behav -key {Behavioral:sim_1:Functional:tb_1} -tclbatch tb_1.tcl -view /home/aelysium/OneDrive/Polimi/3o_anno/reti_logiche/progetto/progetto_rl/tb_1_behav.wcfg -view /home/aelysium/OneDrive/Polimi/3o_anno/reti_logiche/progetto/progetto_rl/tb_1_func_synth.wcfg -log simulate.log

